"""Add absences table

Revision ID: 150c060c43a5
Revises: b8fb53aac90f
Create Date: 2026-05-01 13:43:38.255435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150c060c43a5'
down_revision = 'b8fb53aac90f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('absences')
    # ### end Alembic commands ###
