"""Add user ownership to employees

Revision ID: 331be1928fa6
Revises: 9cf8a18ce3c3
Create Date: 2026-05-07 18:02:06.767474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331be1928fa6'
down_revision = '9cf8a18ce3c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
