"""Add distribution entries table

Revision ID: 7c224c59e9c1
Revises: a55641ddbad1
Create Date: 2026-05-01 13:49:42.398795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c224c59e9c1'
down_revision = 'a55641ddbad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distribution_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_off_count', sa.Integer(), nullable=False),
    sa.Column('absence_count', sa.Integer(), nullable=False),
    sa.Column('worked_days', sa.Integer(), nullable=False),
    sa.Column('computed_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('exact_amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('rounded_amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('average_daily_hours_snapshot', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('distribution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['distribution_id'], ['distributions.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('distribution_id', 'employee_id', name='uq_distribution_employee')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distribution_entries')
    # ### end Alembic commands ###
