"""Add distributions table

Revision ID: a55641ddbad1
Revises: 150c060c43a5
Create Date: 2026-05-01 13:46:34.769874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a55641ddbad1'
down_revision = '150c060c43a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_computed_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('total_tip_amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('tip_per_hour', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_exact_amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_rounded_amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('remainder_amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distributions')
    # ### end Alembic commands ###
